// Generated by CoffeeScript 1.8.0
var Fizzbuzz;

Fizzbuzz = (function() {
  function Fizzbuzz() {}

  Fizzbuzz.prototype.isDivisibleBy = function(number, divisor) {
    return number % divisor === 0;
  };

  Fizzbuzz.prototype.isDivisibleByThree = function(number) {
    return this.isDivisibleBy(number, 3);
  };

  Fizzbuzz.prototype.isDivisibleByFive = function(number) {
    return this.isDivisibleBy(number, 5);
  };

  Fizzbuzz.prototype.isDivisibleByFifteen = function(number) {
    return this.isDivisibleBy(number, 15);
  };

  Fizzbuzz.prototype.says = function(number) {
    if (this.isDivisibleByFifteen(number)) {
      return "fizzbuzz";
    }
    if (this.isDivisibleByThree(number)) {
      return "fizz";
    }
    if (this.isDivisibleByFive(number)) {
      return "buzz";
    } else {
      return number;
    }
  };

  return Fizzbuzz;

})();

module.exports = Fizzbuzz;
